# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3a1b9ea59f3e1e679e9d310901db19515e5db54790d5e7ceabe21c5acf42c027f4f1c202ca77d9ddca8423a1c89d5391c7d53f3be4ee3caf984feb1574ad8a5

test:
  secret_key_base: 054d4db6919032190bf1d905969d5cd75776114f3cc7c1c16f4de0834095a82e2c632a0df03d3e4ddb6552510dba65ac7c31170eb73e8476681347cb9af84e43

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
